version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stacknotesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  workspace-service:
    image: workspace-service
    ports:
      - "8080:8080"

  document-service:
    image: document-service
    ports:
      - "8031:8031"
    depends_on:
      - postgres
      - workspace-service