spring:
  application:
    name: document
  datasource:
    url: jdbc:postgresql://localhost:5432/stacknotesdb
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
services:
  workspace:
    base-url: http://workspace-service/api/v1/workspace
server:
  port: 8031